export const RemoteKey = {
  DpadUp: 'DPAD_UP',
  DpadDown: 'DPAD_DOWN',
  DpadLeft: 'DPAD_LEFT',
  DpadRight: 'DPAD_RIGHT',
  Ok: 'OK',
  Back: 'BACK',
  Home: 'HOME',
  Power: 'POWER',
  VolumeUp: 'VOLUME_UP',
  VolumeDown: 'VOLUME_DOWN',
  Mute: 'MUTE',
  ChannelUp: 'CHANNEL_UP',
  ChannelDown: 'CHANNEL_DOWN',
  PlayPause: 'PLAY_PAUSE',
  Rewind: 'REWIND',
  FastForward: 'FAST_FORWARD',
  Digit0: 'DIGIT_0',
  Digit1: 'DIGIT_1',
  Digit2: 'DIGIT_2',
  Digit3: 'DIGIT_3',
  Digit4: 'DIGIT_4',
  Digit5: 'DIGIT_5',
  Digit6: 'DIGIT_6',
  Digit7: 'DIGIT_7',
  Digit8: 'DIGIT_8',
  Digit9: 'DIGIT_9',
} as const;

export type RemoteKey = (typeof RemoteKey)[keyof typeof RemoteKey];
